export const site_clearance = [
    {
        "id":1,
        "project_name": "Simba",
        "project_manager": "Tevin Kelvin",
        "labour_power": 15,
        "vendor": "Jengo Construction Ltd",
        "reasons_for_choosing_vendor": "Experienced in large-scale site clearance and offers competitive pricing.",
        "budget": "500,000",
        "description_of_budget_usage": "200,000/= for heavy machinery rental, 150,000/= for labor wages, 100,000/= for transportation, and 50,000/= for contingencies.",
        "status": true,
        "C.E.O_remarks": "Approved, proceed with the project.",
        "created_at": "2024-08-15T08:00:00Z"
    },
    {
        "id":2,
        "project_name": "Tembo",
        "project_manager": "Jane Doe",
        "labour_power": 20,
        "vendor": "Kazi Bora Co.",
        "reasons_for_choosing_vendor": "Known for efficient and timely project completion.",
        "budget": "750,000",
        "description_of_budget_usage": "300,000/= for labor wages, 250,000/= for equipment hire, and 200,000/= for material costs.",
        "status": false,
        "C.E.O_remarks": "Pending review, adjust budget allocation.",
        "created_at": "2024-08-15T08:15:00Z"
    },
    {
        "id":3,
        "project_name": "Twiga",
        "project_manager": "Michael Johnson",
        "labour_power": 10,
        "vendor": "SiteClear Solutions",
        "reasons_for_choosing_vendor": "Offers modern equipment and has positive client feedback.",
        "budget": "400,000",
        "description_of_budget_usage": "150,000/= for machinery, 100,000/= for labor, 100,000/= for site preparation, and 50,000/= for unexpected expenses.",
        "status": true,
        "C.E.O_remarks": "Approved, ensure timeline adherence.",
        "created_at": "2024-08-15T08:30:00Z"
    },
    {
        "id":4,
        "project_name": "Kiboko",
        "project_manager": "Alice Williams",
        "labour_power": 18,
        "vendor": "Watu Wetu Ltd",
        "reasons_for_choosing_vendor": "Local expertise with a focus on environmental preservation.",
        "budget": "600,000",
        "description_of_budget_usage": "250,000/= for environmentally friendly equipment, 200,000/= for labor, 100,000/= for site access and logistics, and 50,000/= for safety measures.",
        "status": true,
        "C.E.O_remarks": "Approved, prioritize safety.",
        "created_at": "2024-08-15T08:45:00Z"
    },
    {
        "id":5,
        "project_name": "Chui",
        "project_manager": "Robert Brown",
        "labour_power": 12,
        "vendor": "ClearSite Africa",
        "reasons_for_choosing_vendor": "Specializes in difficult terrains and remote locations.",
        "budget": "550,000",
        "description_of_budget_usage": "200,000/= for specialized equipment, 150,000/= for labor, 100,000/= for transportation, and 100,000/= for risk management.",
        "status": false,
        "C.E.O_remarks": "Revise vendor selection, consider alternatives.",
        "created_at": "2024-08-15T09:00:00Z"
    },
    {
        "id":6,
        "project_name": "Nyati",
        "project_manager": "Emily Davis",
        "labour_power": 25,
        "vendor": "Pamoja Contractors",
        "reasons_for_choosing_vendor": "Well-established with a track record of successful large-scale projects.",
        "budget": "800,000",
        "description_of_budget_usage": "400,000/= for heavy machinery, 200,000/= for labor, 100,000/= for site logistics, and 100,000/= for project management.",
        "status": true,
        "C.E.O_remarks": "Approved, proceed with full force.",
        "created_at": "2024-08-15T09:15:00Z"
    },
    {
        "id":7,
        "project_name": "Punda",
        "project_manager": "David Wilson",
        "labour_power": 8,
        "vendor": "Green Earth Ltd",
        "reasons_for_choosing_vendor": "Specializes in eco-friendly site clearance solutions.",
        "budget": "300,000",
        "description_of_budget_usage": "100,000/= for eco-friendly equipment, 100,000/= for labor, 50,000/= for transportation, and 50,000/= for site preparation.",
        "status": false,
        "C.E.O_remarks": "Review the environmental impact assessment before proceeding.",
        "created_at": "2024-08-15T09:30:00Z"
    },
    {
        "id":8,
        "project_name": "Kifaru",
        "project_manager": "Sarah Thompson",
        "labour_power": 22,
        "vendor": "Jua Kali Works",
        "reasons_for_choosing_vendor": "Provides affordable services with a strong focus on local labor employment.",
        "budget": "700,000",
        "description_of_budget_usage": "300,000/= for labor, 200,000/= for equipment, 100,000/= for logistics, and 100,000/= for safety and welfare.",
        "status": true,
        "C.E.O_remarks": "Approved, ensure local community involvement.",
        "created_at": "2024-08-15T09:45:00Z"
    }
]
